name: Renovate

on:
  schedule:
  - cron: '0/15 * * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        type: choice
        required: true
        default: "info"
        options:
        - "info"
        - "debug"

env:
  LOG_LEVEL: ${{ github.event.inputs.logLevel || 'info' }}

jobs:
  renovate:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Renovate
      uses: renovatebot/github-action@79dc0ba74dc3de28db0a7aeb1d0b95d5bf5fde2a # v46.1.13
      with:
        configurationFile: renovate-global.json
        token: ${{ secrets.RENOVATE_TOKEN }}
