name: Renovate

on:
  schedule:
  - cron: '0/15 * * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        type: choice
        required: true
        default: "info"
        options:
        - "info"
        - "debug"

env:
  LOG_LEVEL: ${{ github.event.inputs.logLevel || 'info' }}

jobs:
  renovate:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Renovate
      uses: renovatebot/github-action@3064367f740a1a91cca218698a63902689cce200 # v46.1.20
      with:
        configurationFile: renovate-global.json
        token: ${{ secrets.RENOVATE_TOKEN }}
