name: Renovate

on:
  schedule:
  - cron: '0/15 * * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        type: choice
        required: true
        default: "info"
        options:
        - "info"
        - "debug"

env:
  LOG_LEVEL: ${{ github.event.inputs.logLevel || 'info' }}

jobs:
  renovate:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Renovate
      uses: renovatebot/github-action@8217b3fc286df088d7c27f3255fe8414463bc0fd # v46.1.15
      with:
        configurationFile: renovate-global.json
        token: ${{ secrets.RENOVATE_TOKEN }}
