name: Static Analysis

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  renovate-validation:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
       node-version: 24

    - name: Validate Repository Renovate Config
      run: npx -y --package renovate -- renovate-config-validator renovate.json

    - name: Validate Global Renovate Config
      run: npx -y --package renovate -- renovate-config-validator renovate-global.json

    - name: Validate Renovate Default Preset
      run: npx -y --package renovate -- renovate-config-validator default.json
